### ISSUE TITLE
MDF File Metadata Issues

### ISSUE THREAD

**Issue by simonkimi** [ihedvall/mdflib#100]
Hello! 

I am using the .NET MDF library to generate MDF files, but I am encountering some issues when inserting metadata.

My code is as follows. When AddCommonProperty is commented out, the generated file works fine. The context is as follows:
```csharp
using System;
using MdfLibrary;

var writer = new MdfWriter(MdfWriterType.Mdf4Basic);
writer.Init("./demo.mdf");

var header = writer.Header;
header.StartTime = (ulong)(DateTimeOffset.Now.ToUnixTimeMilliseconds() * 1000000);

header.Author = "DemoAuthor";

// header.MetaData.AddCommonProperty(new MdfETag
// {
//     Name = "Test",
//     ValueAsString = "Test1",
//     Type = "string"
// });

var meta = header.MetaData;

writer.InitMeasurement();
writer.FinalizeMeasurement();
writer.Dispose();
```

![图片](https://github.com/user-attachments/assets/efd95c0e-3bbe-42b5-8c8a-a3bc2c9476a9)

![图片](https://github.com/user-attachments/assets/f1bb96e3-f734-4276-853f-60668d1997e6)

However, after uncommenting the AddCommonProperty part, an XML header was added to the XmlSnippet, which caused both the [Vector MDF Validator](https://www.vector.com/int/en/products/application-areas/ecu-calibration/measurement/mdf/) and [asammdf](https://asammdf.readthedocs.io/en/latest/index.html) to fail to recognize it.

![图片](https://github.com/user-attachments/assets/c1c41c1d-d9a4-491f-9d0b-025645379265)

![图片](https://github.com/user-attachments/assets/28af305e-dd9b-47fb-bc9f-ff86001cc46b)
English: Invalid XML: Invalid XML declaration

![图片](https://github.com/user-attachments/assets/13e0834e-c349-4eb3-9c73-207d27a52226)

After reviewing the code, I found that skip_header in [IXmlFile::WriteString](https://github.com/ihedvall/mdflib/blob/20c135d82ede75805fe7883eb7ef4091c456ebff/mdflib/src/imetadata.cpp#L160) was set to false. I am not sure whether this is a bug, a feature of MDF, or if there is an issue with how I am using it.

Another issue: I want to fully customize my MetaData, but before I set any values like `header.Author`,`header.MetaData` is null. I don't know how to initialize it.

Looking forward to your guidance.

**Comment by ihedvall** [comment]
I am computers are offline for some days but it have been issues with this earlier. I will be online again in the weekend.14 aug. 2024 kl. 04:01 skrev GugeFramework ***@***.***>:﻿
Hello!
I am using the .NET MDF library to generate MDF files, but I am encountering some issues when inserting metadata.
My code is as follows. When AddCommonProperty is commented out, the generated file works fine. The context is as follows:
using System;
using MdfLibrary;

var writer = new MdfWriter(MdfWriterType.Mdf4Basic);
writer.Init("./demo.mdf");

var header = writer.Header;
header.StartTime = (ulong)(DateTimeOffset.Now.ToUnixTimeMilliseconds() * 1000000);

header.Author = "DemoAuthor";

// header.MetaData.AddCommonProperty(new MdfETag
// {
//     Name = "Test",
//     ValueAsString = "Test1",
//     Type = "string"
// });

var meta = header.MetaData;

writer.InitMeasurement();
writer.FinalizeMeasurement();
writer.Dispose();
default.png (view on web)
default.png (view on web)
However, after uncommenting the AddCommonProperty part, an XML header was added to the XmlSnippet, which caused both the Vector MDF Validator and asammdf to fail to recognize it.
default.png (view on web)
default.png (view on web)
English: Invalid XML: Invalid XML declaration
default.png (view on web)
After reviewing the code, I found that skip_header in IXmlFile::WriteString was set to false. I am not sure whether this is a bug, a feature of MDF, or if there is an issue with how I am using it.
Another issue: I want to fully customize my MetaData, but before I set any values like header.Author,header.MetaData is null. I don't know how to initialize it.
Looking forward to your guidance.

**Comment by ihedvall** [comment]
I am offline for some days but it has been problem with this before. I will back in the weekend.

**Comment by simonkimi** [comment]
No worries at all. I’ve temporarily resolved the issue by creating a fork. We can discuss it further when you’re ready.

**Comment by ihedvall** [comment]
I have corrected the bug in the C++ library. Two calls to the WriteString(true) was missing the argument true. I suppose this will solve the initial problem. The C++

I normally build the .NET C++/CLI wrapper with the Visual Studio solution (mdflibrary.sln/vcxproj).  I will check the .NET interface tomorrow as it was original designed for read-only support.

**Comment by ihedvall** [comment]
I have added a MdfHeader::CreateMetaData() function that either return the existing object or creates a new one. I have not checked but .NET should have some XML library that could generate XML string in/out without a header. 

However there are a lot of improvements to add to the .NET interface regarding the meta data. The C++ library have some more features that the .NET wrapper is missing.
