### ISSUE TITLE
Get macos CI build running

### ISSUE THREAD

**Issue by Murmele** [ihedvall/mdflib#11]

**Comment by ihedvall** [comment]
The main problem seems to be the source_location that MSVC and GCC uses while the CLANG doesn't support. There is several alternative solutions on this issue,

1. Use MSVC and GCC as compiler.
2. Rewrite the MdfLogStream so it doesn't use the source_location. This requires a fork or #ifdef:s inside the streamer class. 
3. Wait until CLANG version support C++ 20 libraries.

**Comment by Murmele** [comment]
I think changing to GCC is fine. Neverthless to compile then with labplot I have to check if it is possible to build for all systems

**Comment by ihedvall** [comment]
I have changed the cmake to use FetchContent build instead of FindPackage for expat in the utillib. This seems to working as the library is small. The same should work for the mdflib build. Assume that the zlib also should be build  the FetchContent way.

**Comment by Murmele** [comment]
is source_location the only c++20 feature which is used?

**Comment by ihedvall** [comment]
No. 
Also ranges are used and most likely some other features. Labplot require C++11 and C99.

**Comment by Murmele** [comment]
Yes currently c++11 and c99 are used. I got labplot compiled with c++20 I have to talk with them If we should upgrade the project to c++20.

**Comment by ihedvall** [comment]
I might be a good idea to upgrade to modern standard. Note that most C++20 code lines can be changed to C++ 11 standard. It is some days work but should work. I let you decide. It depends how old Labplot compilers should support. 

Do you know any tool that can check for c++ 11/20 issues?

**Comment by Murmele** [comment]
You mean some quality checks?
kde is using something in their CI pipeline: https://invent.kde.org/education/labplot/-/merge_requests/157
![image](https://user-images.githubusercontent.com/10099533/194703638-0c8c376b-b68c-4842-818c-33fef123a35b.png)

But currently we don't consider it.
I think it is cppcheck: http://cppcheck.net/

**Comment by ihedvall** [comment]
I have some idea to start using the vcpkg for loading the third-party libraries. Any recommendations regarding this approach?
