### ISSUE TITLE
Typo in the tag?

### ISSUE THREAD

**Issue by kenji-miyake** [ihedvall/mdflib#36]
@ihedvall Hello, thank you for developing this great library! :smile: 
I noticed that there is a comma in the tag: https://github.com/ihedvall/mdflib/releases/tag/v2.0.%2C0.
I'd appreciate it if you could confirm it.
Thank you. :bow:

**Comment by ihedvall** [comment]
Yes. It is a erroneous extra comma in the tag name. Renaming tag names seems to be a tricky GIT operation, so if it isn't any problem, I would leave it as it is. The next release will include the CAN Logger writer. 

There exist an MDF project for requirement requests. I can add you as contributor.

Best Regards
