### ISSUE TITLE
Build problem on Windows

### ISSUE THREAD

**Issue by kozmad** [ihedvall/mdflib#40]
Dear Developers,

I'm writing to you since I'm quite interested in your project. Thank you for providing such a good tool.
I was trying to build the project on my local computer on Windows, using preset msvc-multi-vcpkg-x64, 
but unfortunately, I got the following issue while compiling the mdflibrary project:

[main] Building folder: mdflib 
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build C:/works/mdflib/build/msvc-multi-vcpkg-x64 --config Debug --target ALL_BUILD
[build] MSBuild version 17.5.1+f6fdcf537 for .NET Framework
[build] 
[build]   1>Checking Build System
[build]   mdf.vcxproj -> C:\mdflib\build\msvc-multi-vcpkg-x64\mdflib\Debug\mdfd.lib
[build]   MdfExport.cpp
**[build] C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\condition_variable(27,1): fatal  error C1189: #error:  <condition_variable> is not supported when compiling with /clr or /clr:pure. [C:\mdflib\build\msvc-multi-vcpkg-x64\mdflibrary\mdflibrary.vcxproj]**
[build]   AssemblyInfo.cpp
[build]   MdfAttachment.cpp
[build]   MdfChannel.cpp
[build]   MdfChannelArray.cpp
[build]   MdfChannelConversion.cpp
[build]   MdfChannelGroup.cpp
[build]   MdfChannelObserver.cpp
[build]   MdfDataGroup.cpp
[build]   MdfETag.cpp
[build]   MdfEvent.cpp
[build]   MdfFile.cpp
[build]   MdfFileHistory.cpp
[build]   MdfHeader.cpp
[build]   mdflibrary.cpp
[build]   MdfMetaData.cpp
[build]   MdfReader.cpp
[build]   MdfSourceInformation.cpp
[build]   MdfWriter.cpp
**[build] C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\condition_variable(27,1): fatal  error C1189: #error:  <condition_variable> is not supported when compiling with /clr or /clr:pure. [C:\mdflib\build\msvc-multi-vcpkg-x64\mdflibrary\mdflibrary.vcxproj]**
[build]   Generating Code...
[build]   mdfview.vcxproj -> C:\mdflib\build\msvc-multi-vcpkg-x64\mdfviewer\Debug\mdfview.exe
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --build C:/mdflib/build/msvc-multi-vcpkg-x64 --config Debug --target ALL_BUILD exited with code: 1
[driver] Build completed: 00:00:26.124
**[build] Build finished with exit code 1**

The mdflib and mdfviewer has been build completely.

Could you help me, what could be the problem here?

Thank you for your help in advance!

Best regards,
Daniel

**Comment by ihedvall** [comment]
Yes this is a build problem for the MDF .NET assembly. It is a known problem with mutex, thread and conditions that cannot be included in .NET. The solution is normally to move some include files from the cpp-files. I take a look at it

**Comment by kozmad** [comment]
Thank you for your quick answer and help. Sorry, if I haven't noticed the bug ticket on this.

**Comment by Simplxss** [comment]
please use MSVC above 14.36, or disable building shared lib.

**Comment by kozmad** [comment]
Thank you! Temporarily I disable it, but I'll test it as soon as I can.

**Comment by ihedvall** [comment]
I have test to compile the assembly and it is working OK.  According to Simplxss, this error went away by upgrading the VS2022. I tested with 14.37.

There might be a solution for this type of problem by wrapping the failing include file with pragma unmanaged/managed. I cannot verify it but if you have time, you can do a fast test? 

MdfWriter.h
```
#pragma managed(push, off)
#include <condition_variable>
#pragma managed(pop)
```

**Comment by kozmad** [comment]
Thank you!
I've just cleaned and rebuilt the project, but unfortunately adding pragmas does not solve the issue.

Best regards,
Daniel

**Comment by ihedvall** [comment]
This problem disappeared with never MSVC.  Tricky to find a solution as I cannot reproduce the problem.

**Comment by Simplxss** [comment]
> This problem disappeared with never MSVC. Tricky to find a solution as I cannot reproduce the problem.

It is not our problem, just MSVC(<= 14.35.32215) does not support `condition_variable`.

Please see [Changelog of VS 2022 17.6](https://github.com/microsoft/STL/wiki/Changelog#vs-2022-176)

> The STL now supports /clr for C++11 multithreading (mutex, condition_variable, future, etc.) and C++17 parallel algorithms. Additionally, the STL now allows /clr to be used in C++20 mode. [#3194](https://github.com/microsoft/STL/pull/3194) [#3201](https://github.com/microsoft/STL/pull/3201)
> See tracking issue [#3193](https://github.com/microsoft/STL/issues/3193) for a list of compiler bugs that affect these newly enabled /clr scenarios.

The best way to solve it is updating your Visual Studio.

**Comment by kozmad** [comment]
Sorry, for the delayed response, I've just had time to check this out.
Indeed, the upgrade solves the problem instantly.
