### ISSUE TITLE
Problem using mdflib in custom project

### ISSUE THREAD

**Issue by TheElesty** [ihedvall/mdflib#49]
When trying to use mdflib (installed using .exe file in both main and release 2.0.0), I am unable to compile the test project. Tested in CLion with Visual Studio 2017/2022 and NMake generator

MDF lib v2.0.0
CLion with NMake generator:
![image](https://github.com/ihedvall/mdflib/assets/32326985/5a3eacdf-9dc8-43c6-a87f-a71909a1427e)

CLion with Visual Studio 15 2017 generator:
![image](https://github.com/ihedvall/mdflib/assets/32326985/9c3287dc-01e8-41aa-b6c4-a3f0ebae32be)

CLion with Visual Studio 17 2022 generator:
![image](https://github.com/ihedvall/mdflib/assets/32326985/59caa852-f82e-4a68-baff-127413c9e772)

Visual Studio 2022:
![image](https://github.com/ihedvall/mdflib/assets/32326985/e85e07d9-efd3-484b-afd5-54cad80bdc91)

When using version form main (using CLion with Visual Studio 15 2017 generator) I got this:
![image](https://github.com/ihedvall/mdflib/assets/32326985/23e88c1a-2cdd-4053-8a73-cd3deb88b88f)
![image](https://github.com/ihedvall/mdflib/assets/32326985/259cf9b8-06c6-4249-b75d-dc13e3ca57ae)

I tried also to build lib from source, but without success (again in both vs17 and vs22). I was able to build mdflib target in vs 17, but for mdflibrary I got an error that build tools are incorrect, and even after retargeting solution it won't change.

**Comment by ihedvall** [comment]
Sorry that building causing problem. The best way to build is to use cmake. The CMakeList.txt configuration file unfortunately have the MDF_SHARED_LIB=ON. This means that also the C# interface is built which CMake handle but not CLion. If you turn off the C# interface build, most of your errors will disappear.

The MDF library is dependent on 2-5 external libraries,The C++ library depends on ZLIB and EXPAT. The unit test is dependent on the Google Unit test while the MdfViewer are dependent on WxWindows and Boost.

Basically there exist 3 different way to solve external dependencies. The first solution is to use an external component path. See the COMP_DIR option below. This is the preferred solution if "you" are many user of the library. This is typical used by companies. The ihedvall/components repository includes script files for building external libraries. 

The second way is to replace the component path with vcpkg. The vcpkg is little bit funky but it will build all external dependencies for you on the fly. It will take some more compilation time at the first build (boost and wxWindows). This functionality is newly added.

The third way is let CMake download the external libraries if they are missing. This works OK for smaller libraries as Google unit test, ZLIB and expat but doesn't work for GUI (boost/wxWindows) . I think this is your current mode.

My current CLion settings are as below:  
![image](https://github.com/ihedvall/mdflib/assets/92839244/2edfb367-ec38-4562-83c7-0be6199bcf53)

**Comment by Simplxss** [comment]
Please build mdf library before building mdf_test.
I think you need a chicken before you want a egg.

**Comment by TheElesty** [comment]
> Please build mdf library before building mdf_test. I think you need a chicken before you want a egg.

mdf_test is my testing project using mdf.lib from instalator

**Comment by Simplxss** [comment]
Sorry, I have not seen that you are using the library from installator.
Can you try to use the .lib from github action?
https://github.com/ihedvall/mdflib/actions/runs/6019755660

**Comment by TheElesty** [comment]
Thank, will try both suggestion and I let u know if that worked

**Comment by ihedvall** [comment]
I don't like this .NET Framework... stuff in the compiler. Just wondering if the /clr compiler option is set in Visual Studio ?

**Comment by TheElesty** [comment]
So using prebuild lib from github action works. Thanks for fast response

**Comment by TheElesty** [comment]
So Im testing the mdf-lib, I have similar erros as, when i was building mdeflib from source, I got a lot of _LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2'_	errors for debug, and some errors about linking EXPAT (and maybe zlib), I had both expat and zlib installed manually, but probably some wrong versions, cos it missed something from zlib (zlibstatic.lib or similar)
