### ISSUE TITLE
Reader example not working

### ISSUE THREAD

**Issue by Murmele** [ihedvall/mdflib#5]
Currently I am trying to get the example working, but for me it is not working:

![image](https://user-images.githubusercontent.com/10099533/192090472-46f34eb8-f185-44c7-9850-11402808f81a.png)

**Comment by ihedvall** [comment]
Yes it's a bug. It should be obs-> not sub->

**Comment by ihedvall** [comment]
Many unit test require some test file(s). Unfortunately, most files are proprietary of a company. I am also missing MDF3 files.  

This is a common problem. so normally I solve this by checking if the remote direcctory exist and if not, don't run the test (well they always succeed).

I don't know if this is the best solution.

**Comment by Murmele** [comment]
> 

I think it should at least compile. I made a proposal in #7 how to achieve this

**Comment by ihedvall** [comment]
Not perfect solution but it doesn't break anything
