### ISSUE TITLE
Compressed mf4 file Vector Validator warnings

### ISSUE THREAD

**Issue by jezzzzza** [ihedvall/mdflib#51]
When saving mf4 with compressed option

![image](https://github.com/ihedvall/mdflib/assets/38853146/fdfe1a47-ce84-40df-bcea-f04364425576)

One get following error and warning readings in Vector [MDF Validator Tool](https://www.vector.com/de/de/download/mdf-validator/)

![image](https://github.com/ihedvall/mdflib/assets/38853146/f74acfaf-1a00-4ec1-8770-e336167031dd)

Not sure if that is really a problem though, since the data can be read normally..

Btw, many thanks for providing that mdflib project!

**Comment by ihedvall** [comment]
Fixed the length error. It was the type and reserved bytes that wasn't written.
