### ISSUE TITLE
Reading string and byte array from compressed mf4 not working..

### ISSUE THREAD

**Issue by jezzzzza** [ihedvall/mdflib#56]
Reading string or byte array data from compressed mf4 channel group does not work.

**Comment by ihedvall** [comment]
I have found the error. It will merge in at the same time I fix the  Reference problem (.NET minor fix in CC block). To late today so I do i tomorrow.

**Comment by jezzzzza** [comment]
Thank you very much @ihedvall !

**Comment by ihedvall** [comment]
I think I can close this bug know. Unit test added for this for this bug

**Comment by jezzzzza** [comment]
Thank you, i can also confirm that byte array reading works for compressed mf4 file, thank you!
