### ISSUE TITLE
All floats are written as 64bit

### ISSUE THREAD

**Issue by afestini** [ihedvall/mdflib#72]
https://github.com/ihedvall/mdflib/blob/16b8f111ee66388ed741687445674cdefc92a932/mdflib/src/cn4block.cpp#L1012

the code compares the given byte size against bit sizes, resulting in the cases never matching and defaulting to 64bit.

**Comment by ihedvall** [comment]
Thanks for finding the bug. I will correct the code ASAP.

**Comment by ihedvall** [comment]
Fixed the bug so 4 and 8 bytes floats are supported. 2 bytes float are supported for reading but not for writing.
