### ISSUE TITLE
Potential bug, compression error?

### ISSUE THREAD

**Issue by jezzzzza** [ihedvall/mdflib#76]
Im doing this

![image](https://github.com/ihedvall/mdflib/assets/38853146/ab6815ac-d91c-409b-8978-d5236bd36144)

with compression set to true earlier in the code

![image](https://github.com/ihedvall/mdflib/assets/38853146/52eaf03f-2eb4-4f1a-8a41-7b7b9a0645f7)

Vector MDF validator gives me this errors

![image](https://github.com/ihedvall/mdflib/assets/38853146/f3be438d-c58f-4e42-afd3-16d87bb61274)

im using this commit from mdflib --> 9c7a6fedc4d742fbb4e2ddcbf975ee0ee46b4226

**Comment by ihedvall** [comment]
Thanks for finding bugs.

I'm repainting my working room why my main computer is disconnected. It may take some days before I can check the error. I suspect that the data to store is less than 100 byte which is the lower limit for compressing. You can copy the TestWrite::CompressData unit test so it shows your error. In TestWrite::*, all files are saved in the "%TEMP%/test/mdf/write" directory until next run so you may. 

Note: I found some other errors with some flags which should also be corrected.

**Comment by ihedvall** [comment]
@jezzzzza 
I have modified the CompressData unit test but it seems to be working OK. I'm using the latest release. It suspect it may be some error with the channel definition (array/string?) and compress. Can you give me little bit information  about the how you configured the channel and channel group?

**Comment by ihedvall** [comment]
I think I have found the error. I suspect I need to add a HL block to the compressed SD block. Need to check the specification. I return in a day or so.
