### ISSUE TITLE
Showing linked information in tree

### ISSUE THREAD

**Issue by Murmele** [ihedvall/mdflib#8]
Is it possible to directly showing the metadata directly in the table instead of just (link to unit?)
![image](https://user-images.githubusercontent.com/10099533/192146999-a9a23d0e-c945-4730-b4da-159196c28f8b.png)

**Comment by ihedvall** [comment]
Well maybe. I only have one line to show data in or at maybe multiline may work. I could check if the TXT or the MD block only consist of a "one liner" text, then showing the contents instead of the link. I can see what can be done

**Comment by Murmele** [comment]
Or maybe when clicking on the link showing the content in a dialog?

**Comment by ihedvall** [comment]
A double click should either show pop-up or set the tree-list to the block. Note that the link may me NULL i.e. pointing on nothing.

**Comment by ihedvall** [comment]
I have checked in the changes so the TX/MD blocks "main" text are show in the description field. 

Still in the GUI, is the bitmap problem. Windows uses BITMAP format while Unix and MacOS uses some other format (PNG?). I'm setting up an Ubuntu computer for development but it take some days before it works.
