### ISSUE TITLE
Solving the BITMAP issue in the GUI

### ISSUE THREAD

**Issue by ihedvall** [ihedvall/mdflib#9]
The wxwidgets is platform dependent regading bitmap thats are used in the GUI. This need to be investigated and fixed.

**Comment by Murmele** [comment]
I will check it out

**Comment by Murmele** [comment]
I hope I get tomorrow again time to check it out

**Comment by ihedvall** [comment]
I have solved that problem in utillib GUI:s. I have an ubuntu development machine now. The solution is to convert ICO and BMP files to XPM files. Include and ifdef windows and non-windows. 

I fix this issue. I'm working with windows mdflib build today, so I fix this tomorrow.

**Comment by ihedvall** [comment]
In linux, replace the bitmap with an XPM file. This solves the problem in Linux.
